//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_bankimg_services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int employeeID { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
    }
}
