//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_bankimg_services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerdata
    {
        public int customerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phnumber { get; set; }
        public string MailID { get; set; }
    }
}
